name: Code Quality tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    strategy:
      matrix:
        dependencies:
          - "locked"
          - "highest"
        php-version:
          - "8.0"
          - "8.1"
        operating-system:
          - "ubuntu-latest"

    runs-on: ${{ matrix.operating-system }}

    steps:
      - uses: actions/checkout@v2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          extensions: mbstring, intl, zip, soap, gd
          coverage: xdebug #optional, setup coverage driver
          tools: composer:v2

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"
          restore-keys: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Install locked dependencies"
        if: ${{ matrix.dependencies == 'locked' }}
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: Run Lint Checker suite
        run: composer php-lint

      - name: Run PHP Stan
        run: composer phpstan

      - name: Run test suite
        run: composer test